game:
  windowSize: [1200, 800]
  interval: 0.05
  scale: 8
  enable_control: False
  show:
    car: True
    pos: False
    vel: False
    acc: False
    vel_multiplier: 5
    acc_multiplier: 5
    kf_mean: False
    kf_var: False

sim:
  target_n_cars: 1
  spawn_frame_interval: 10
  report_frame_interval: 100
  measurement_noise: 0
  randomize: False