game:
  windowSize: [1200, 800]
  interval: 0.05
  scale: 8
  enable_control: True
  show:
    car: True
    pos: True
    vel: True
    acc: True
    vel_multiplier: 5
    acc_multiplier: 15
    kf_mean: False
    kf_var: False

sim:
  target_n_cars: 1
  spawn_frame_interval: 10
  report_frame_interval: 100
  measurement_noise: 0
  randomize: False

